# -*- coding: utf-8 -*-
"""Topsis_for_pretrained_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1UQEVZj2PLDnDG6oJEp3pTapGZGtaol8B
"""

import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import os

# -----------------------------
# Create output folder
# -----------------------------
OUTPUT_DIR = "results"
os.makedirs(OUTPUT_DIR, exist_ok=True)

# -----------------------------
# Text Classification Data
# -----------------------------
data = {
    "Domain": ["Politics"]*4 + ["Sports"]*4 + ["Medicine"]*4,
    "Model": ["BERT", "RoBERTa", "DistilBERT", "ALBERT"] * 3,
    "Accuracy": [7.83, -1.01, 2.40, 8.74, 0.96, 4.44, -9.61, 9.37, 5.49, 8.90, 8.69, -7.39],
    "Precision": [10.98, 3.62, 10.91, 0.97, -9.29, -6.32, -2.23, 2.50, -2.34, 0.29, 0.95, -5.99],
    "Recall": [-9.58, 7.06, -4.62, -2.14, -6.55, 4.55, 9.53, -0.85, 9.98, 1.20, 10.41, -0.25],
    "F1": [-4.12, 2.92, -6.66, -9.91, -6.21, -6.16, -8.54, -6.13, 6.68, 5.67, 6.58, 4.93],
    "Inference_Time": [1.73, 4.69, 3.67, 2.27, 4.06, -2.61, 5.45, 5.23, -6.68, -0.01, -8.71, 9.74],
    "Model_Size": [6.37, 6.74, -8.05, -9.55, 0.17, -0.46, -5.93, 3.42, 2.09, -7.58, -4.57, 8.31]
}

df = pd.DataFrame(data)

# -----------------------------
# TOPSIS Function
# -----------------------------
def topsis(domain_df):
    criteria_matrix = domain_df.iloc[:, 2:].values
    num_criteria = criteria_matrix.shape[1]

    # Equal weights
    weights = np.ones(num_criteria) / num_criteria

    # Normalization
    normalized = criteria_matrix / np.sqrt((criteria_matrix ** 2).sum(axis=0))
    weighted = normalized * weights

    # Benefit and cost criteria indices
    benefit_idx = [0, 1, 2, 3]
    cost_idx = [4, 5]

    ideal_best = np.zeros(num_criteria)
    ideal_worst = np.zeros(num_criteria)

    ideal_best[benefit_idx] = weighted[:, benefit_idx].max(axis=0)
    ideal_best[cost_idx] = weighted[:, cost_idx].min(axis=0)

    ideal_worst[benefit_idx] = weighted[:, benefit_idx].min(axis=0)
    ideal_worst[cost_idx] = weighted[:, cost_idx].max(axis=0)

    # Distance measures
    d_positive = np.sqrt(((weighted - ideal_best) ** 2).sum(axis=1))
    d_negative = np.sqrt(((weighted - ideal_worst) ** 2).sum(axis=1))

    # TOPSIS score
    domain_df["TOPSIS Score"] = d_negative / (d_positive + d_negative)
    domain_df["Rank"] = domain_df["TOPSIS Score"].rank(ascending=False)

    return domain_df.sort_values("Rank")

# -----------------------------
# Apply TOPSIS Domain-wise
# -----------------------------
all_results = []

for domain in df["Domain"].unique():
    domain_data = df[df["Domain"] == domain].copy()
    ranked_data = topsis(domain_data)
    all_results.append(ranked_data)

    # -------- Plot --------
    plt.figure(figsize=(6, 4))
    plt.bar(ranked_data["Model"], ranked_data["TOPSIS Score"])
    plt.xlabel("Models")
    plt.ylabel("TOPSIS Score")
    plt.title(f"TOPSIS Scores for {domain} Domain")
    plt.tight_layout()
    plt.savefig(f"{OUTPUT_DIR}/{domain}_topsis_graph.png")
    plt.close()

final_df = pd.concat(all_results)

# -----------------------------
# Save Results
# -----------------------------
final_df.to_csv(f"{OUTPUT_DIR}/text_classification_topsis_results.csv", index=False)

print("\nFINAL TOPSIS RESULT TABLE:\n")
print(final_df[["Domain", "Model", "TOPSIS Score", "Rank"]])